apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orderservice-postgres
spec:
  serviceName: orderservice-postgres
  replicas: 1
  selector:
    matchLabels:
      app: orderservice-postgres
  template:
    metadata:
      labels:
        app: orderservice-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: system-config
                  key: DB_ORDER_SERVICE
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: system-secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: system-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi