name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write
  statuses: write

env:
  MODULE_PATH: .
  GRADLE_PROJECT_NAME: UserService
  JAVA_VERSION: '21'
  GRADLE_VERSION: '8.14.3'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        options: --name redis_server --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 6379:6379

      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        options: --name postgres_server --health-cmd "pg_isready -U testuser -d testdb" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show workspace (for debugging)
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          ls -la .
          echo "=== find first-level dirs ==="
          find . -maxdepth 2 -type d -print

      - name: Detect module path (find gradlew)
        id: detect
        run: |
          if [ -x "./gradlew" ] || [ -f "./gradlew" ]; then
            echo "MODULE_PATH=." >> $GITHUB_ENV
          else
            FOUND=$(find . -maxdepth 4 -type f -name gradlew -printf '%h\n' | head -n 1 || true)
            if [ -n "$FOUND" ]; then
              STRIPPED=${FOUND#./}
              echo "MODULE_PATH=$STRIPPED" >> $GITHUB_ENV
            else
              echo "MODULE_PATH=." >> $GITHUB_ENV
            fi
          fi
          echo "Detected MODULE_PATH = $MODULE_PATH"

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Ensure gradlew is executable
        run: chmod +x "${{ env.MODULE_PATH }}/gradlew"

      - name: 1. Build UserService (Skip Tests)
        working-directory: ${{ env.MODULE_PATH }}
        run: ./gradlew build -x test

      - name: Wait for Database and Redis Services
        run: |
          for i in $(seq 1 10); do 
            nc -z -w 1 postgres 5432 && echo "Postgres is up!" && break
            echo "Waiting for Postgres... ($i)"
            sleep 1
          done
          for i in $(seq 1 10); do 
            nc -z -w 1 redis 6379 && echo "Redis is up!" && break
            echo "Waiting for Redis... ($i)"
            sleep 1
          done

      - name: 2. Run Unit and Integration Tests
        working-directory: ${{ env.MODULE_PATH }}
        env:
          SPRING_REDIS_HOST: redis
          SPRING_REDIS_PORT: 6379
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testdb
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: testpassword
          SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
          TESTCONTAINERS_REUSE_ENABLE: true
        run: ./gradlew test

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UserService-jar
          path: ${{ env.MODULE_PATH }}/build/libs/*.jar
          retention-days: 1

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Unit Tests
          path: ${{ env.MODULE_PATH }}/build/test-results/test/TEST-*.xml
          reporter: java-junit

  sonarqube-analysis:
    needs: build-and-test
    runs-on: ubuntu-latest
    # Поднимаем SonarQube как сервис-контейнер, доступный по хосту 'sonarqube'
    services:
      sonarqube:
        image: sonarqube:10-community
        ports:
          - 9000:9000
        options: >-
          --name sonarqube_server
          --health-cmd "curl -f http://localhost:9000/api/system/health || exit 1"
          --health-interval 10s --health-timeout 5s --health-retries 30
  
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Detect module path (find gradlew)
        id: detect-sonar
        run: |
          if [ -x "./gradlew" ] || [ -f "./gradlew" ]; then
            echo "MODULE_PATH=." >> $GITHUB_ENV
          else
            FOUND=$(find . -maxdepth 4 -type f -name gradlew -printf '%h\n' | head -n 1 || true)
            STRIPPED=${FOUND#./}
            echo "MODULE_PATH=${STRIPPED:-.}" >> $GITHUB_ENV
          fi
          echo "Detected MODULE_PATH = $MODULE_PATH"
  
      - name: Ensure gradlew is executable
        run: chmod +x "${{ env.MODULE_PATH }}/gradlew"
  
      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
  
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
  
      - name: Wait for SonarQube to be healthy and obtain SONAR_TOKEN
        # SECRET_SONAR_TOKEN содержит значение секретного токена, если он задан в репозитории.
        env:
          SECRET_SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          set -euo pipefail
  
          echo "Waiting for SonarQube HTTP API at http://sonarqube:9000 ..."
          for i in $(seq 1 60); do
            status=$(curl -sS http://sonarqube:9000/api/system/health || true)
            if echo "$status" | grep -qi '"status":"GREEN"'; then
              echo "SonarQube is healthy."
              break
            fi
            echo "Waiting for SonarQube... ($i/60)"
            sleep 5
          done
  
          # Если пользователь заранее положил секрет SONAR_TOKEN в репозиторий — используем его.
          if [ -n "${SECRET_SONAR_TOKEN:-}" ]; then
            echo "Using SONAR_TOKEN from repository secrets."
            echo "SONAR_TOKEN=$SECRET_SONAR_TOKEN" >> $GITHUB_ENV
            exit 0
          fi
  
          echo "No SONAR_TOKEN secret provided — attempting to create a token via SonarQube API (admin:admin)."
          # Попытка сгенерировать token через API; имя токена уникальное по run id.
          resp=$(curl -sS -u admin:admin -X POST "http://sonarqube:9000/api/user_tokens/generate" -d "name=gha-token-${GITHUB_RUN_ID}" || true)
          token=$(echo "$resp" | grep -oP '"token":"\K[^"]+' || true)
  
          if [ -n "$token" ]; then
            echo "Token created successfully."
            echo "SONAR_TOKEN=$token" >> $GITHUB_ENV
          else
            echo "Failed to create token automatically. Response:"
            echo "$resp"
            echo
            echo "If SonarQube requires a different admin password, or token creation is disabled, add a SONAR_TOKEN secret in repository settings."
            exit 1
          fi
  
      - name: Build and run Sonar analysis against local SonarQube
        working-directory: ${{ env.MODULE_PATH }}
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        run: |
          set -euo pipefail
          echo "Running Gradle build + Sonar analysis against SonarQube at http://sonarqube:9000"
          ./gradlew build sonar --info \
            -Dsonar.host.url=http://sonarqube:9000 \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.projectKey="${{ github.repository }}/UserService" \
            -Dsonar.sources=src/main/java \
            -Dsonar.tests=src/test/java \
            -Dsonar.java.binaries=build/classes/java/main


  docker-build-push:
    needs: sonarqube-analysis
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: UserService-jar
          path: ${{ env.MODULE_PATH }}/build/libs/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 4. Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.MODULE_PATH }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/user-service:latest
            ghcr.io/${{ github.repository_owner }}/user-service:${{ github.sha }}
