apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  type: NodePort
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
    - name: external
      port: 9094
      targetPort: 9094
      nodePort: 30032